<?php
// The main Web application configurations.
Yii::setPathOfAlias('editable', dirname(__FILE__).'/../extensions/x-editable');
return array(
    'basePath' => dirname(__FILE__) . DIRECTORY_SEPARATOR . '..',
    'charset' => 'UTF-8',
    'id' => 'com.jebmarket.webapp',
    'language' => 'en',
    'sourceLanguage'=>'en_us',
    'name' => 'JebMarket',
    'timeZone'=>'UTC', # for PHP
    'theme' => 'jebmarket',
    # 'preload' => array('log'),
    # autoloading model and component classes
    # ---------------------------------------
    'import' => array(
        'application.models.*',
        'application.components.*',
        'application.modules.rights.*',
        'application.modules.rights.components.*',
        'editable.*',
        'application.modules.reports.*',
        'application.modules.reports.components.*',
     ),
    'modules' => array(
        # Gii tool
        # -----------
        'gii' => array(
            'class' => 'system.gii.GiiModule',
            'password' => 'mustbedisableonproduction',
            'ipFilters' => array('*', '::1'),
        ),
        # Authorization Rights
        # --------------------
        'rights'=>array(
            'superuserName' => 'JebAdmin',
            'authenticatedName' => 'Registered',
            'flashSuccessKey'=>'success',
            'flashErrorKey'=>'error',
            'appLayout'=>'application.themes.jebmarket.views.layouts.main',
            'layout'=>'application.themes.jebmarket.views.rights.layout',
            'displayDescription'=>false,
            'cssFile' => false,
            'enableBizRule'=>false,
            'enableBizRuleData'=>false,
            'debug'=>false,
            # For Installer
            # 'install'=> true,
            # 'superUsers'=>array(
            # 40=>'jebadmin',
            # ),
        ),
        'reports',
        'blog',
        # Shop
        # --------------------------------
        'store' => array(
            'debug' => true,
            'install' => true,
            'transactionType' => array(
                '1' => 'Free',
                '2' => 'Percentage Share',
                '3' => 'Fixed'
            ),
            'successFlashKey'=>'success',
            'warningFlashKey'=>'warning',
            'errorFlashKey'=>'danger',
            'infoFlashKey'=>'info',
        )
    ),
    'components' => array(
        # Theme
        # ------------------
        'themeManager' => array(
            'basePath' => dirname(__FILE__) . '/../themes',
        ),
        # jQuery
        # ---------------------
        'clientScript' => array(
            'scriptMap' => array(
                'jquery.min.js' => 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js',
            ),
        ),
        # In-place Edit
        # ---------------
        'editable' => array(
            'class'     => 'editable.EditableConfig',
            'form'      => 'plain',
            'mode'      => 'inline',
            'defaults'  => array(
                'emptytext' => 'Click to Add'
            )
        ),
        # User
        # --------
        'user' => array(
            'allowAutoLogin' => true,
            'class' => 'RWebUser',
            'guestName' => 'Guest',
        ),
        # Hit Counter for dashboard, can be removed or replaces with pwik
        'counter' => array(
            'class' => 'UserCounter',
        ),
        # SEF URL
        # ----------
        'urlManager' => array(
            'urlFormat' => 'path',
            'showScriptName' => false,
            'rules' => array(
                'gii' => 'gii',
                #'gii/<controller:\w+>' => 'gii/<controller>',
                #'gii/<controller:\w+>/<action:\w+>' => 'gii/<controller>/<action>',
                #'rights/<controller:\w+>' => 'rights/<controller>',
                #'rights/<controller:\w+>/<action:\w+>' => 'rights/<controller>/<action>',
                array(
                    'class' => 'application.components.ProfileUrlRule',
                    'connectionID' => 'db',
                ),
                'blog/admin' => 'blog/default/admin',
                '<module:\w+>/<controller:\w+>' => '<module>/<controller>',
                '<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>/<view:\w+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ),
        ),
        # Database Access
        # ---------------
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=jassifie_yii_jeb',
            'emulatePrepare' => true,
            #'username' => 'root',
            #'password' => '1234',
            'username' => 'jassifie_yiijeb',
            'password' => '99.9%available',
            'charset' => 'utf8',
            'initSQLs'=>array("set time_zone='+00:00';"),
        ),
        # Authorization Manager
        # ------------------------
        'authManager' => array(
            'class' => 'RDbAuthManager',
            'connectionID' => 'db',
            'assignmentTable' => 'jebapp_auth_assignment',
            'itemTable' => 'jebapp_auth_item',
            'itemChildTable' => 'jebapp_auth_item_child',
            'rightsTable' => 'jebapp_rights',
            'defaultRoles' => array('Guest'),
        ),
        # Default Error Handler (controller/action)
        # ------------------------
        'errorHandler' => array(
            'errorAction' => 'site/error',
        ),
        # Application Log
        # -----------------
        'log' => array(
            'class' => 'CLogRouter',
            'routes' => array(
                array(
                    'class' => 'CFileLogRoute',
                    'levels' => 'error, warning',
                ),
                # uncomment the following to show log messages on web pages on development.
                #  array(
                #          'class'=>'CWebLogRoute',
                #  )
            ),
        ),
    ),
    # Application-level parameters, Yii::app()->params['paramName']
    # -------------------------------------------------------------
    'params' => array(
        'sitemenu' => array(
            'site/contact' => 'Contact',
            'site/login' => 'Login',
            'site/logout' => 'Logout',
            'faq' => 'FAQ',
            'user/profile' => 'User Profile',
            'blog' => 'Blog'
        ),
        'usermenu' => array(
            'userBlock' => array('label' => 'User', 'linkOptions' => array('class' => 'list-group-title')),
            'dashboard' => array('label' => '<span class="glyphicon glyphicon-th"></span> Dashboard', 'url' => array('/dashboard')),
            'profile' => array('label' => '<span class="glyphicon glyphicon-user"></span> Profile', 'url' => array('/user/profile')),
            'password' => array('label' => '<span class="glyphicon glyphicon-lock"></span> Change Password', 'url' => array('/user/changepass')),

            'websiteBlock' => array('label' => 'WebSite', 'linkOptions' => array('class' => 'list-group-title')),
            'blog' => array('label' => '<span class="glyphicon glyphicon-list-alt"></span> Blog', 'url' => array('/blog/admin')),
            'pages' => array('label' => '<span class="glyphicon glyphicon-edit"></span> Pages', 'url' => array('/pages/admin')),
            'settings' => array('label' => '<span class="glyphicon glyphicon-cog"></span> Settings', 'url' => array('/website/admin')),

            'storeBlock' => array('label' => 'Store', 'linkOptions' => array('class' => 'list-group-title')),
            'myStore' => array('label' => '<span class="glyphicon glyphicon-th"></span> My Store', 'url' => array('/store')),
            'storeProducts' => array('label' => '<span class="glyphicon glyphicon-barcode"></span> Products', 'url' => array('/store/product')),
            'storeCategories' => array('label' => '<span class="glyphicon glyphicon-th-list"></span> Categories', 'url' => array('/store/category')),
            'storeSettings' => array('label' => '<span class="glyphicon glyphicon-cog"></span> Settings', 'url' => array('/store/store/settings')),
            'storeCustomers' => array('label' => '<span class="glyphicon glyphicon-user"></span> Customers', 'url' => array('/store/customer')),
            'storeOrders' => array('label' => '<span class="glyphicon glyphicon-inbox"></span> Orders', 'url' => array('/store/order')),

            'reportBlock' => array('label' => 'Reports', 'linkOptions' => array('class' => 'list-group-title')),
            'reports' => array('label' => '<span class="glyphicon glyphicon-stats"></span> Reports', 'url' => array('/reports')),

        ),
        'adminmenu' => array(
            array('label' => 'Sliders', 'url' => array('/slider/admin'), 'itemOptions'=>array('class'=>'slider') ),
            array('label' => 'Email Templates', 'url' => array('/emailTemplate/admin'), 'itemOptions'=>array('class'=>'emailtemplate')),
            array('label' => 'FAQs', 'url' => array('/faq/admin'), 'itemOptions'=>array('class'=>'faqs')),
            array('label' => 'Users', 'url' => array('/user/admin'), 'itemOptions'=>array('class'=>'users')),
            array('label' => 'User Access', 'url' => array('/rights'), 'itemOptions'=>array('class'=>'useraccess')),
            array('label' => 'Locations', 'url' => array('/location/admin'), 'itemOptions'=>array('class'=>'locations')),
            array('label' => 'Settings', 'url' => array('/settings/index'), 'itemOptions'=>array('class'=>'settings')),
            array('label' => 'Store Module', 'url' => array('/store/store/admin'), 'itemOptions'=>array('class'=>'store')),
        ),
        'portlets' => array(
            'userStatistics'=> array('name' => 'userStatistics', 'title' => 'Users Statistics', 'sticky' => false,),
            'userStatus'=> array('name' => 'userStatus', 'title' => 'Users Status', 'sticky' => false),
            'userTwitter'=> array('name' => 'userTwitter', 'title' => 'Twitter ', 'sticky' => false),
            'userFacebook'=> array('name' => 'userFacebook', 'title' => 'Facebook', 'sticky' => false),
        ),
        # ISO 639-1 Language Codes
        # -------------------------
        'lang' => array(
            'aa' => 'Afar',
            'ab' => 'Abkhaz',
            'ae' => 'Avestan',
            'af' => 'Afrikaans',
            'ak' => 'Akan',
            'am' => 'Amharic',
            'an' => 'Aragonese',
            'ar' => 'Arabic',
            'as' => 'Assamese',
            'av' => 'Avaric',
            'ay' => 'Aymara',
            'az' => 'Azerbaijani',
            'ba' => 'Bashkir',
            'be' => 'Belarusian',
            'bg' => 'Bulgarian',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bm' => 'Bambara',
            'bn' => 'Bengali',
            'bo' => 'Tibetan Standard, Tibetan, Central',
            'br' => 'Breton',
            'bs' => 'Bosnian',
            'ca' => 'Catalan; Valencian',
            'ce' => 'Chechen',
            'ch' => 'Chamorro',
            'co' => 'Corsican',
            'cr' => 'Cree',
            'cs' => 'Czech',
            'cu' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
            'cv' => 'Chuvash',
            'cy' => 'Welsh',
            'da' => 'Danish',
            'de' => 'German',
            'dv' => 'Divehi; Dhivehi; Maldivian;',
            'dz' => 'Dzongkha',
            'ee' => 'Ewe',
            'el' => 'Greek, Modern',
            'en' => 'English',
            'eo' => 'Esperanto',
            'es' => 'Spanish; Castilian',
            'et' => 'Estonian',
            'eu' => 'Basque',
            'fa' => 'Persian',
            'ff' => 'Fula; Fulah; Pulaar; Pular',
            'fi' => 'Finnish',
            'fj' => 'Fijian',
            'fo' => 'Faroese',
            'fr' => 'French',
            'fy' => 'Western Frisian',
            'ga' => 'Irish',
            'gd' => 'Scottish Gaelic; Gaelic',
            'gl' => 'Galician',
            'gn' => 'GuaranÃ­',
            'gu' => 'Gujarati',
            'gv' => 'Manx',
            'ha' => 'Hausa',
            'he' => 'Hebrew (modern)',
            'hi' => 'Hindi',
            'ho' => 'Hiri Motu',
            'hr' => 'Croatian',
            'ht' => 'Haitian; Haitian Creole',
            'hu' => 'Hungarian',
            'hy' => 'Armenian',
            'hz' => 'Herero',
            'ia' => 'Interlingua',
            'id' => 'Indonesian',
            'ie' => 'Interlingue',
            'ig' => 'Igbo',
            'ii' => 'Nuosu',
            'ik' => 'Inupiaq',
            'io' => 'Ido',
            'is' => 'Icelandic',
            'it' => 'Italian',
            'iu' => 'Inuktitut',
            'ja' => 'Japanese (ja)',
            'jv' => 'Javanese (jv)',
            'ka' => 'Georgian',
            'kg' => 'Kongo',
            'ki' => 'Kikuyu, Gikuyu',
            'kj' => 'Kwanyama, Kuanyama',
            'kk' => 'Kazakh',
            'kl' => 'Kalaallisut, Greenlandic',
            'km' => 'Khmer',
            'kn' => 'Kannada',
            'ko' => 'Korean',
            'kr' => 'Kanuri',
            'ks' => 'Kashmiri',
            'ku' => 'Kurdish',
            'kv' => 'Komi',
            'kw' => 'Cornish',
            'ky' => 'Kirghiz, Kyrgyz',
            'la' => 'Latin',
            'lb' => 'Luxembourgish, Letzeburgesch',
            'lg' => 'Luganda',
            'li' => 'Limburgish, Limburgan, Limburger',
            'ln' => 'Lingala',
            'lo' => 'Lao',
            'lt' => 'Lithuanian',
            'lu' => 'Luba-Katanga',
            'lv' => 'Latvian',
            'mg' => 'Malagasy',
            'mh' => 'Marshallese',
            'mi' => 'Maori',
            'mk' => 'Macedonian',
            'ml' => 'Malayalam',
            'mn' => 'Mongolian',
            'mr' => 'Marathi (Mara?hi)',
            'ms' => 'Malay',
            'mt' => 'Maltese',
            'my' => 'Burmese',
            'na' => 'Nauru',
            'nb' => 'Norwegian BokmÃ¥l',
            'nd' => 'North Ndebele',
            'ne' => 'Nepali',
            'ng' => 'Ndonga',
            'nl' => 'Dutch',
            'nn' => 'Norwegian Nynorsk',
            'no' => 'Norwegian',
            'nr' => 'South Ndebele',
            'nv' => 'Navajo, Navaho',
            'ny' => 'Chichewa; Chewa; Nyanja',
            'oc' => 'Occitan',
            'oj' => 'Ojibwe, Ojibwa',
            'om' => 'Oromo',
            'or' => 'Oriya',
            'os' => 'Ossetian, Ossetic',
            'pa' => 'Panjabi, Punjabi',
            'pi' => 'Pali',
            'pl' => 'Polish',
            'ps' => 'Pashto, Pushto',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'rm' => 'Romansh',
            'rn' => 'Kirundi',
            'ro' => 'Romanian, Moldavian, Moldovan',
            'ru' => 'Russian',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanskrit (Sa?sk?ta)',
            'sc' => 'Sardinian',
            'sd' => 'Sindhi',
            'se' => 'Northern Sami',
            'sg' => 'Sango',
            'si' => 'Sinhala, Sinhalese',
            'sk' => 'Slovak',
            'sl' => 'Slovene',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somali',
            'sq' => 'Albanian',
            'sr' => 'Serbian',
            'ss' => 'Swati',
            'st' => 'Southern Sotho',
            'su' => 'Sundanese',
            'sv' => 'Swedish',
            'sw' => 'Swahili',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'tg' => 'Tajik',
            'th' => 'Thai',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmen',
            'tl' => 'Tagalog',
            'tn' => 'Tswana',
            'to' => 'Tonga (Tonga Islands)',
            'tr' => 'Turkish',
            'ts' => 'Tsonga',
            'tt' => 'Tatar',
            'tw' => 'Twi',
            'ty' => 'Tahitian',
            'ug' => 'Uighur, Uyghur',
            'uk' => 'Ukrainian',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            've' => 'Venda',
            'vi' => 'Vietnamese',
            'vo' => 'VolapÃ¼k',
            'wa' => 'Walloon',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'za' => 'Zhuang, Chuang',
            'zh' => 'Chinese',
            'zu' => 'Zulu',
        )
    ),
);